CREATE TABLE users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,  -- Use VARCHAR(255) to store a hashed password
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
